# Generated by Django 3.1.1 on 2020-09-15 20:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import license.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('license', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=120, unique=True)),
                ('poc_contact_name', models.CharField(max_length=120)),
                ('poc_contact_email', models.EmailField(max_length=254)),
                ('admin_poc', models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package', models.PositiveSmallIntegerField(choices=[('javascript_sdk', 0), ('ios_sdk', 1), ('android_sdk', 2)])),
                ('license_type', models.PositiveSmallIntegerField(choices=[('production', 0), ('evaluation', 1)])),
                ('created_datetime', models.DateTimeField(auto_now=True)),
                ('expiration_datetime', models.DateTimeField(default=license.models.get_default_license_expiration)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='license.client')),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
