# Generated by Django 3.1.1 on 2020-09-16 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0002_auto_20200915_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='license_type',
            field=models.IntegerField(choices=[('0', 'Javascript_sdk'), ('1', 'Ios_sdk'), ('2', 'Android_sdk')]),
        ),
        migrations.AlterField(
            model_name='license',
            name='package',
            field=models.IntegerField(choices=[('0', 'Production'), ('0', 'Evaluation')], max_length=1),
        ),
    ]
