# Generated by Django 3.1.1 on 2020-09-16 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0003_auto_20200916_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='package',
            field=models.IntegerField(choices=[('0', 'Production'), ('0', 'Evaluation')]),
        ),
    ]
