# Generated by Django 3.1.1 on 2020-09-16 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0004_auto_20200916_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='license_type',
            field=models.IntegerField(choices=[('js', 'Javascript_sdk'), ('ios', 'Ios_sdk'), ('android', 'Android_sdk')]),
        ),
        migrations.AlterField(
            model_name='license',
            name='package',
            field=models.IntegerField(choices=[('Production', 'Production'), ('Evaluation', 'Evaluation')]),
        ),
    ]
