# Generated by Django 3.1.1 on 2020-09-16 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0007_auto_20200916_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='license_type',
            field=models.CharField(blank=True, choices=[('js', 'Javascript_sdk'), ('ios', 'Ios_sdk'), ('android', 'Android_sdk')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='license',
            name='package',
            field=models.CharField(blank=True, choices=[('Production', 'Production'), ('Evaluation', 'Evaluation')], max_length=15, null=True),
        ),
    ]
